name: Wade Wegner
permalink: /:year/:month/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "Gemfile"]
markdown: redcarpet
pygments: true
title : Wade Wegner
tagline: From the whiteboard to the keyboard

author :
  name : Wade Wegner
  email : wade.wegner@gmail.com
  github : wadewegner
  twitter : wadewegner
  feedburner : WadeWegner

categories_path : /categories.html
archive_path: /archive.html

disqus :
  short_name : wadewegner
  url : http://www.wadewegner.com

google : 
  tracking_id : 'UA-1174672-2'